services:

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "9090:80"
    environment:
      - PMA_ARBITRARY=1

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - ./dbfiles:/docker-entrypoint-initdb.d
    environment:
       MYSQL_ROOT_PASSWORD: qwerty
       MYSQL_DATABASE: sistema_ventas_db
       MYSQL_USER: admin
       MYSQL_PASSWORD: admin


  sistema-ventas-back:
    build:
      context: ./sistema-ventas-back
      dockerfile: Dockerfile
    container_name: sistema-ventas-back
    ports:
      - "8080:3000"
    environment:
      DB_HOST: mysql-db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: sistema_ventas_db
    depends_on:
      - mysql-db
    restart: unless-stopped 

  sistema-ventas-front:
    build:
      context: ./angular
      dockerfile: Dockerfile
    image: nginx:latest
    container_name: sistema-ventas-front
    ports:
      - "80:80"
    depends_on:
      - sistema-ventas-back