# stack
version: '3.8'

services:
  # Servicio MySQL
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - ./dbfiles:/docker-entrypoint-initdb.d  # Monta carpeta con scripts SQL
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: sistema_ventas_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: unless-stopped
  
  # Servicio phpMyAdmin 
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "9090:80"
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mysql-db
    restart: unless-stopped

 # Servicio Backend (Node.js)
  backend:
    build:
      context: ./sistema-ventas-back
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql-db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: sistema_ventas_db
    depends_on:
      - mysql-db
    restart: unless-stopped

  # Servicio Frontend (Angular)
  frontend:
    build:
      context: ./angular
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped 